create extension if not exists pgcrypto;

create table if not exists public.stations (
    station_id text primary key,
    station_name text not null,
    corridor text not null,
    latitude numeric(9, 6) not null,
    longitude numeric(9, 6) not null,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    constraint stations_latitude_ck check (latitude between -90 and 90),
    constraint stations_longitude_ck check (longitude between -180 and 180)
);

create table if not exists public.datasets (
    dataset_id uuid primary key default gen_random_uuid(),
    dataset_name text not null,
    source_url text not null,
    api_version text not null,
    content_hash text not null,
    cutoff_at timestamptz not null,
    ingested_at timestamptz not null default now(),
    constraint datasets_name_cutoff_uq unique (dataset_name, cutoff_at)
);

create table if not exists public.context (
    observed_at timestamptz primary key,
    dataset_id uuid not null references public.datasets(dataset_id),
    rain_mm numeric,
    rain_forecast numeric,
    temperature_c numeric,
    temperature_forecast numeric,
    event_intensity numeric,
    created_at timestamptz not null default now()
);

create table if not exists public.observations (
    observation_id bigint generated by default as identity primary key,
    dataset_id uuid not null references public.datasets(dataset_id),
    station_id text not null references public.stations(station_id),
    observed_at timestamptz not null references public.context(observed_at),
    demand integer not null,
    ingested_at timestamptz not null default now(),
    constraint observations_station_time_uq unique (station_id, observed_at),
    constraint observations_demand_ck check (demand >= 0)
);

create table if not exists public.feature_snapshots (
    feature_snapshot_id uuid primary key default gen_random_uuid(),
    dataset_id uuid not null references public.datasets(dataset_id),
    version text not null unique,
    feature_config jsonb not null default '{}'::jsonb,
    artifact_uri text,
    created_at timestamptz not null default now()
);

create table if not exists public.model_versions (
    model_version_id uuid primary key default gen_random_uuid(),
    feature_snapshot_id uuid not null references public.feature_snapshots(feature_snapshot_id),
    version text not null unique,
    git_commit text not null,
    training_cutoff timestamptz not null,
    feature_config jsonb not null default '{}'::jsonb,
    status text not null default 'candidate',
    created_at timestamptz not null default now(),
    constraint model_versions_status_ck check (status in ('candidate', 'active', 'retired', 'failed'))
);

create table if not exists public.pipeline_runs (
    run_id uuid primary key default gen_random_uuid(),
    model_version_id uuid references public.model_versions(model_version_id),
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    data_cutoff timestamptz not null,
    status text not null default 'running',
    error_message text,
    constraint pipeline_runs_status_ck check (status in ('running', 'succeeded', 'failed', 'skipped')),
    constraint pipeline_runs_finished_ck check (finished_at is null or finished_at >= started_at)
);

create table if not exists public.predictions (
    prediction_id bigint generated by default as identity primary key,
    run_id uuid not null references public.pipeline_runs(run_id) on delete cascade,
    station_id text not null references public.stations(station_id),
    target_at timestamptz not null,
    horizon_minutes integer not null,
    predicted_demand numeric not null,
    created_at timestamptz not null default now(),
    constraint predictions_run_station_target_horizon_uq
        unique (run_id, station_id, target_at, horizon_minutes),
    constraint predictions_horizon_ck check (horizon_minutes > 0),
    constraint predictions_demand_ck check (predicted_demand >= 0)
);

create table if not exists public.metrics (
    metric_id bigint generated by default as identity primary key,
    run_id uuid not null references public.pipeline_runs(run_id) on delete cascade,
    station_id text references public.stations(station_id),
    metric_name text not null,
    metric_value numeric not null,
    window_start timestamptz not null,
    window_end timestamptz not null,
    created_at timestamptz not null default now(),
    constraint metrics_window_ck check (window_end >= window_start)
);

create table if not exists public.drift_events (
    drift_event_id bigint generated by default as identity primary key,
    run_id uuid not null references public.pipeline_runs(run_id) on delete cascade,
    metric_name text not null,
    observed_value numeric not null,
    threshold numeric not null,
    severity text not null,
    detected_at timestamptz not null default now(),
    details jsonb not null default '{}'::jsonb,
    constraint drift_events_severity_ck check (severity in ('info', 'warning', 'critical'))
);

create index if not exists observations_time_idx on public.observations (observed_at);
create index if not exists observations_dataset_idx on public.observations (dataset_id);
create index if not exists context_dataset_idx on public.context (dataset_id);
create index if not exists predictions_station_target_idx on public.predictions (station_id, target_at);
create index if not exists metrics_run_idx on public.metrics (run_id);
create index if not exists drift_events_run_idx on public.drift_events (run_id);

alter table public.stations enable row level security;
alter table public.datasets enable row level security;
alter table public.context enable row level security;
alter table public.observations enable row level security;
alter table public.feature_snapshots enable row level security;
alter table public.model_versions enable row level security;
alter table public.pipeline_runs enable row level security;
alter table public.predictions enable row level security;
alter table public.metrics enable row level security;
alter table public.drift_events enable row level security;

create policy "authenticated users can read pulso data"
    on public.stations for select to authenticated using (true);
create policy "authenticated users can read pulso datasets"
    on public.datasets for select to authenticated using (true);
create policy "authenticated users can read pulso context"
    on public.context for select to authenticated using (true);
create policy "authenticated users can read pulso observations"
    on public.observations for select to authenticated using (true);
create policy "authenticated users can read pulso features"
    on public.feature_snapshots for select to authenticated using (true);
create policy "authenticated users can read pulso models"
    on public.model_versions for select to authenticated using (true);
create policy "authenticated users can read pulso runs"
    on public.pipeline_runs for select to authenticated using (true);
create policy "authenticated users can read pulso predictions"
    on public.predictions for select to authenticated using (true);
create policy "authenticated users can read pulso metrics"
    on public.metrics for select to authenticated using (true);
create policy "authenticated users can read pulso drift events"
    on public.drift_events for select to authenticated using (true);
