create table if not exists public.forecast_predictions (
    cycle_id text not null,
    client_run_id text not null,
    submission_id text,
    station_id text not null,
    target_at timestamptz not null,
    data_cutoff timestamptz not null,
    horizon_minutes integer not null check (horizon_minutes > 0),
    predicted_demand numeric not null check (predicted_demand >= 0),
    created_at timestamptz not null default now(),
    primary key (cycle_id, station_id, target_at)
);

create index if not exists forecast_predictions_target_idx
    on public.forecast_predictions (target_at);

create table if not exists public.wape_drift_checks (
    drift_check_id bigint generated by default as identity primary key,
    current_window_start timestamptz not null,
    current_window_end timestamptz not null,
    reference_wape numeric,
    current_wape numeric,
    relative_increase numeric,
    threshold numeric not null,
    reference_count integer not null default 0,
    current_count integer not null default 0,
    drift_detected boolean not null default false,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    processed_at timestamptz,
    constraint wape_drift_window_ck check (current_window_end >= current_window_start)
);

create index if not exists wape_drift_pending_idx
    on public.wape_drift_checks (created_at)
    where drift_detected and processed_at is null;

alter table public.forecast_predictions enable row level security;
alter table public.wape_drift_checks enable row level security;
